### ISSUE TITLE
What are suitable datasets that we can use to do the workshop

### ISSUE THREAD

**Issue by jurra** [the-magnificents/04-02-2021-Carpentry-for-HGIS#1]
We decided to use population, and geospatial lat long, data, for this workshop.
 
## Data set for demonstration
- [x] Find the dataset for the Netherlands as a basis dataset
(We will then also try to create data with python)

**Comment by aecryan** [comment]
I will give a try to creating a custom coordinate system from lat/long coords following the suggestion from the turtle graphics repo owner. We could maybe use this in an assignment, but tbh I think it will be more trouble than it's worth to revise oregon data and the whole example ....let's see if it works :)
