### ISSUE TITLE
Does anaconda come with jupyter lab?

### ISSUE THREAD

**Issue by jurra** [the-magnificents/04-02-2021-Carpentry-for-HGIS#19]
Hi @aecryan I think it does, at least for windows.
We can double check in Day 1, if they are able to launch jupyter lab, using the command line.

If not we can install it.
[https://github.com/jupyterlab/jupyterlab](https://github.com/jupyterlab/jupyterlab)

**Comment by jurra** [comment]
Here you can see the packages that come with Anaconda for Windows-64: [https://docs.anaconda.com/anaconda/packages/py3.6_win-64/](https://docs.anaconda.com/anaconda/packages/py3.6_win-64/)

**Comment by aecryan** [comment]
Hey I just checked in Mac and it comes with JupyterLab.
