### ISSUE TITLE
Day 2 section on pandas and matplotlib

### ISSUE THREAD

**Issue by jurra** [the-magnificents/04-02-2021-Carpentry-for-HGIS#34]
# Checklist
- [ ] Jupyter notebook starter with notes
- [x] Code ready to go
- [x] Put int the instructor notes folder properly
- [x] Use the airport's data generated by @aecryan
- [x] Count the number of airports per country
- [x] Plot the amount of airports per country
- [x] Filter a country with airports to a smaller data frame
- [x] Separate western airports from eastern
- [x] Take airports in a certain lat range or on a range
- [x] .....

**Comment by aecryan** [comment]
I have code that shows how these data were created from the Python console and how the country code was added. Also the issue with specificity in lat/long coordinates and country borders (some coastal or island airports could not be located inside any country no matter how specific their lat/long coordinates became)
