### ISSUE TITLE
Send pre-survey to learners enrolled in the workshop

### ISSUE THREAD

**Issue by jurra** [the-magnificents/04-02-2021-Carpentry-for-HGIS#6]
Approximately 2 weeks prior to the workshop, please send a reminder to your learners to complete the pre-survey and install the necessary software prior to the workshop. Feel free to utilize the email template "Email Learners before Workshop", found in The Carpentries Handbook. The survey links for learners are automatically generated on the workshop's GitHub page, and typically located above and within the schedule.

**Comment by aecryan** [comment]
Pre-workshop survey - can’t use the one from the Carpentries but maybe can model after. We know participants are beginners and from the faculty of architecture. 

- Engage and motivate
- assumption validation (currently scripting, rate 1-5, archiving data in repo, etc.).
- rate comfort level with three technologies.

**Comment by jurra** [comment]
Find out how aware are participants with regard to data literacy and software literacy,
Maybe asking questions like I do archive my data ,
I code or I am planning to code because I think is important for my research.....

**Comment by aecryan** [comment]
The pre-workshop survey has been drafted here: https://tudelft.fra1.qualtrics.com/jfe/form/SV_3jxek8fPH8Ma7Fc

**Comment by aecryan** [comment]
I sent the survey to the learners today midday.
